---
- name: debug
  debug: var=loader_role

- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-loader container
  template:
    src: o2r-loader.service.j2
    dest: "/etc/systemd/system/{{loader_role.container.name}}.service"
    owner: root
    group: root
    mode: 0600
  register: loadercreate
  tags:
    - loader
    - microservice

- name: Pull image
  when: loadercreate.changed
  become: yes
  docker_image:
    name: "{{loader_role.container.image}}"
    state: present
    source: pull
    force_source: yes
  tags:
    - loader
    - microservice

- name: Enable service
  become: yes
  service:
    name: "{{loader_role.container.name}}"
    enabled: yes
  tags:
    - loader
    - microservice

- meta: flush_handlers
  tags:
    - loader
    - microservice

- name: Start service
  become: yes
  notify: Wait for o2r-loader to start up
  service:
    name: "{{loader_role.container.name}}"
    state: started
  tags:
    - loader
    - microservice

- meta: flush_handlers
  tags:
    - loader
    - microservice
