---
shipper_role:
  config:
    basepath: "{{storage}}"
    port: 8087
    sessionsecret: "{{sessionsecret}}"
    mongo_host: "{{mongo_host}}"
    mongo_port: "{{mongo_port}}"
    mongo_database: "{{mongo_database}}"
    bottle_host: "0.0.0.0"
    zenodo:
      token: "{{zenodo_token}}"
    zenodo_sandbox:
      token: "{{zenodo_sandbox_token}}"
  container:
    image: "o2rproject/o2r-shipper:e1ce0e6"
    name: o2r-shipper
  configdir: "/etc/o2r/shipper"
