---
- name: Create data directory
  become: yes
  file:
    path: "{{shipper_role.config.basepath}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - shipper
    - microservice

- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-shipper container
  template:
    src: o2r-shipper.service.j2
    dest: "/etc/systemd/system/{{shipper_role.container.name}}.service"
    owner: root
    group: root
    mode: 0600
  register: shippercreate
  tags:
    - shipper
    - microservice

- name: Pull image
  when: shippercreate.changed
  become: yes
  docker_image:
    name: "{{shipper_role.container.image}}"
    state: present
    source: pull
    force_source: yes
  tags:
    - shipper
    - microservice

- name: Enable service
  become: yes
  service:
    name: "{{shipper_role.container.name}}"
    enabled: yes
  tags:
    - shipper
    - microservice

- meta: flush_handlers
  tags:
    - shipper
    - microservice

- name: Start service
  become: yes
  notify: Wait for o2r-shipper to start up
  service:
    name: "{{shipper_role.container.name}}"
    state: started
  tags:
    - shipper
    - microservice

- meta: flush_handlers
  tags:
    - shipper
    - microservice
