---
nginx_role:
  container:
    image: "o2rproject/ui:0.5.4"
    #image: "o2rproject/ui:bugfix"
    name: nginx
  ui:
    api_url: "{{ui_api_url}}"
    erc_url: "{{ui_erc_url}}"
    config_path:
      host: "/etc/nginx-docker/config.json"
      container: "/usr/share/nginx/html/config.js"
