---
- name: debug
  debug: var=muncher_role

- name: Create data directory
  become: yes
  file:
    path: "{{muncher_role.config.basepath}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - muncher
    - microservice

- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-muncher container
  template:
    src: o2r-muncher.service.j2
    dest: "/etc/systemd/system/{{muncher_role.container.name}}.service"
    owner: root
    group: root
    mode: 0600
  register: munchercreate
  tags:
    - muncher
    - microservice

- name: Pull image
  when: munchercreate.changed
  become: yes
  docker_image:
    name: "{{muncher_role.container.image}}"
    state: present
    source: pull
    force_source: yes
  tags:
    - muncher
    - microservice

- name: Enable service
  become: yes
  service:
    name: "{{muncher_role.container.name}}"
    enabled: yes
  tags:
    - muncher
    - microservice

- meta: flush_handlers
  tags:
    - muncher
    - microservice

- name: Start service
  become: yes
  notify: Wait for o2r-muncher to start up
  service:
    name: "{{muncher_role.container.name}}"
    state: started
  tags:
    - muncher
    - microservice

- meta: flush_handlers
  tags:
    - muncher
    - microservice