---
- hosts: master
  roles:
    # required databases:
    - docker-mongodb
    - docker-elasticsearch
    # MongoDB admin interface:
    - docker-mongo-express
    # o2r microservices:
    - docker-muncher
    - docker-informer
    - docker-inspecter
    - docker-bouncer
    - docker-finder
    - docker-loader
    - docker-shipper
    - docker-substituter
    - docker-bindings
    - docker-ui
    #- docker-badger
    # proxy (must come after services it proxies):
    - docker-nginx
    # meta:
    - docker-ps
  environment:
    http_proxy: "{{proxy.http_proxy}}"
    https_proxy: "{{proxy.http_proxy}}"
