---
- name: debug
  debug: var=finder_role
  tags:
    - finder
    - microservice

- name: Create service
  become: yes
  notify:
    - Reload Systemd
    - Remove old o2r-finder container
  template:
    src: o2r-finder.service.j2
    dest: "/etc/systemd/system/{{finder_role.container.name}}.service"
    owner: root
    group: root
    mode: 0600
  register: findercreate
  tags:
    - finder
    - microservice

- name: Pull image
  when: findercreate.changed
  become: yes
  docker_image:
    name: "{{finder_role.container.image}}"
    state: present
    source: pull
    force_source: yes
  tags:
    - finder
    - microservice

- name: Enable service
  become: yes
  service: 
    name: "{{finder_role.container.name}}"
    enabled: yes
  tags:
    - finder
    - microservice

- meta: flush_handlers
  tags:
    - finder
    - microservice

- name: Start service
  become: yes
  notify: Wait for o2r-finder to start up
  service:
    name: "{{finder_role.container.name}}"
    state: started
  tags:
    - finder
    - microservice

- meta: flush_handlers
  tags:
    - finder
    - microservice
